services:
  jfc-mariadb:
    image: jfc-db
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    environment:
      MARIADB_USER: jfc
      MARIADB_PASSWORD: jfcP@ssword123!
      MARIADB_DATABASE: jfc
      MARIADB_ROOT_PASSWORD: Password123!
    ports: 
    - 3366:3306
#    volumes:
#      - C:/dev/github.com/vadim-kosarev/jfc-common/jfc-docker/jfc_db/jfc:/var/lib/mysql/jfc
  jfc-minio:
    image: jfc_minio
    build:
      context: .
      dockerfile: Dockerfile.minio
    environment:
      MINIO_ROOT_USER: jfc
      MINIO_ROOT_PASSWORD: jfcP@ssword123!
    ports:
      - 9099:9000
      - 9909:9001
    volumes:
      - C:/Minio:/opt/minio
    tty: true
    entrypoint:
      /bin/minio server /opt/minio --console-address :9001
