services:
  jfc-mariadb:
    image: jfc-db
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    environment:
      MARIADB_USER: jfc-user
      MARIADB_PASSWORD: jfc-user-password
      MARIADB_DATABASE: jfc
      MARIADB_ROOT_PASSWORD: Password123!
    ports: 
    - 3366:3306
    volumes:
      - C:/dev/github.com/vadim-kosarev/jfc-common/jfc-docker/jfc_db/jfc:/var/lib/mysql/jfc
